import "./globals.css";

import { Footer } from "@/components/Footer";
import type { Metadata } from "next";
import { NavbarTop } from "@/components/NavbarTop";
import { SidebarNav } from "@/components/SidebarNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex">
        <SidebarNav />

        <div className="flex-1 flex flex-col">
          <div className="flex flex-col flex-1">
            <NavbarTop />
            {children}
          </div>

          <Footer />
        </div>
      </body>
    </html>
  );
}
