import "./globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        {
          // TODO: Sticky on scroll <SidebarNav />
          // TODO: Sticky on scroll <NavbarTop />
        }

        {children}

        {
          // TODO: Sticky on scroll <Footer />
        }
      </body>
    </html>
  );
}
